# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Build with Gradle Wrapper
      run: ./gradlew build

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        path: |
          fabric/build/libs/*.jar
          forge/build/libs/*.jar
          neoforge/build/libs/*.jar

  check-version:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Get latest release version
      id: release-version
      uses: joutvhu/get-release@v1
      with:
        latest: true
        # Tag name start with `v`
        pattern: '^v.*'
        # Including pre-release
        prerelease: true

    - name: Get version property
      id: current-version
      uses: christian-draeger/read-properties@1.1.1
      with:
        path: gradle.properties
        properties: version

    outputs:
      new-tag-name: ${{ format("v{}", steps.current-version.outputs.version) }}
      is-new-version: ${{ steps.release-version.outputs.tag_name == outputs.new-tag-name }}

  publish:

    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: [build, check-version]
    if: needs.check-version.outputs.is-new-version

    steps:
    - uses: actions/checkout@v4
    - name: Push new version tag
      uses: actions-ecosystem/action-push-tag@v1
      with:
        tag: ${{ needs.check-version.outputs.new-tag-name }}
        message: ${{ needs.check-version.outputs.new-tag-name }}
        
    - uses: actions/download-artifact@v4
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag-name: ${{ needs.check-version.outputs.new-tag-name }}
        files: |
          fabric/build/libs/*[0-9].jar
          forge/build/libs/*[0-9].jar
          neoforge/build/libs/*[0-9].jar      
    

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    # Generates and submits a dependency graph, enabling Dependabot Alerts for all project dependencies.
    # See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
